### PR TITLE
added a video header

### LINKED ISSUE #32: Add a heading before the video in index.html that says `Watch the Video`

### PR DESCRIPTION
**Pull request by AlecNesatColak**
Resolve #32 Successfully added the header for the video

### CODE REVIEW

**Comment by nbkhope** [comment]
@AlecNesatColak Hi, as a reviewer I don't know which issue you are resolving (there are many issues!). Please add

```
Resolve #123
```

to the top of the description of your pull request (not the title), so that the pull request gets linked to the issue you are resolving. Replace 123 with the actual issue number.

**Comment by AlecNesatColak** [comment]
Should be up to date now! Thank you for that feedback, I didn't realize that was how the linked to the issue!

**Review by nbkhope — APPROVED** [review]
Looks good to me (LGTM)!

**Comment by nbkhope** [comment]
@AlecNesatColak yes, GitHub is smart enough to parse the issue number and show it in the sidebar.

Usually when we work in a company, there are thousands of issues, and some people work on multiple issues at the same time, so it's really hard to know exactly what issue the pull request is meant for, even if you take the time to go search for the issue using filters by assignee username.

**Comment by nbkhope** [comment]
@AlecNesatColak next time, try to create a feature branch instead of working directly on master:

```
git checkout master
git checkout -b my-feature-branch
# ... do your work ...
git push origin my-feature-branch
```

Use my-feature-branch for the pull request.

**Pull request merged**
